"""Generate `repos-index.md` — a markdown table of all cached projects.

This is the safe, deterministic half of the original M7 spec from
PLAN.md §8. The auto-write-into-Claude-Code-memory part (M7b) is
deferred until we have an explicit, agreed contract for that path.
For now we produce a markdown file that any AI tool can ingest:
Claude Code via slash command, Codex via file include, or just
`cat repos-index.md` from a chat.

The exporter reads from the SQLite cache, never from disk. That keeps
it as fast as `armillary list` and as side-effect-free.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .cache import Cache
from .models import Project

# Columns in display order. Tuple of (header, key) where key is one of:
#  - "name", "type", "umbrella", "path", "last_modified" — straight from Project
#  - "status", "branch", "dirty", "last_commit", "last_commit_author" — from metadata
#  - "readme" — from metadata.readme_excerpt
_COLUMNS: tuple[tuple[str, str], ...] = (
    ("Name", "name"),
    ("Type", "type"),
    ("Status", "status"),
    ("Branch", "branch"),
    ("Dirty", "dirty"),
    ("Last commit", "last_commit"),
    ("Last modified", "last_modified"),
    ("Path", "path"),
    ("Description", "readme"),
)


def render_repos_index(
    projects: list[Project],
    *,
    title: str = "armillary — projects index",
    generated_at: datetime | None = None,
) -> str:
    """Render a list of `Project`s as a self-contained markdown document.

    The output is intentionally human-readable AND machine-parseable:
    a heading, a generated-at line, the row count, and a markdown table.
    Empty fields render as `—`. README excerpts are stripped of pipes
    and newlines so they do not break the markdown table layout.
    """
    generated_at = generated_at or datetime.now()
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(
        f"Generated by `armillary export-index` at "
        f"{generated_at.strftime('%Y-%m-%d %H:%M:%S')}."
    )
    lines.append("")
    lines.append(f"**{len(projects)}** project(s) in the index.")
    lines.append("")

    if not projects:
        lines.append(
            "_Cache is empty. Run `armillary scan` to populate it, then re-export._"
        )
        lines.append("")
        return "\n".join(lines)

    headers = [h for h, _ in _COLUMNS]
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join(["---"] * len(headers)) + "|")
    for project in projects:
        cells = [_render_cell(project, key) for _, key in _COLUMNS]
        lines.append("| " + " | ".join(cells) + " |")

    lines.append("")
    return "\n".join(lines)


def write_repos_index(
    output_path: Path,
    *,
    db_path: Path | None = None,
    title: str = "armillary — projects index",
) -> int:
    """Read the cache, render the index, and write it to `output_path`.

    Returns the number of projects written. Creates parent directories
    as needed; overwrites the file if it already exists.
    """
    with Cache(db_path=db_path) as cache:
        projects = cache.list_projects()
    output_path = output_path.expanduser()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_repos_index(projects, title=title),
        encoding="utf-8",
    )
    return len(projects)


# --- internals ------------------------------------------------------------


def _render_cell(project: Project, key: str) -> str:
    md = project.metadata
    value: str | None

    if key == "name":
        value = project.name
    elif key == "type":
        value = project.type.value
    elif key == "umbrella":
        value = str(project.umbrella)
    elif key == "path":
        value = str(project.path)
    elif key == "last_modified":
        value = project.last_modified.strftime("%Y-%m-%d")
    elif key == "status":
        value = md.status.value if md and md.status else None
    elif key == "branch":
        value = md.branch if md else None
    elif key == "dirty":
        # `dirty=0` is meaningful ("clean working tree"), distinct from
        # "metadata never extracted" → "—".
        if md is not None and md.dirty_count is not None:
            value = str(md.dirty_count)
        else:
            value = None
    elif key == "last_commit":
        value = (
            md.last_commit_ts.strftime("%Y-%m-%d") if md and md.last_commit_ts else None
        )
    elif key == "last_commit_author":
        value = md.last_commit_author if md else None
    elif key == "readme":
        value = md.readme_excerpt if md else None
    else:  # pragma: no cover — guarded by _COLUMNS
        value = None

    if value is None or value == "":
        return "—"
    return _escape_for_markdown_table(value)


def _escape_for_markdown_table(text: str) -> str:
    """Strip pipes and newlines so a value cannot break a markdown row.

    Pipes get replaced with `\\|` (escaped form, valid GFM). Line
    breaks collapse to spaces. We do not try to clamp length — long
    descriptions are fine and Claude/Codex parse them just as well as
    short ones.
    """
    return text.replace("\n", " ").replace("\r", " ").replace("|", "\\|").strip()
