"""Generate `repos-index.md` — a markdown table of all cached projects.

This is the safe, deterministic half of the original M7 spec from
PLAN.md §8. The auto-write-into-Claude-Code-memory part (M7b) is
deferred until we have an explicit, agreed contract for that path.
For now we produce a markdown file that any AI tool can ingest:
Claude Code via slash command, Codex via file include, or just
`cat repos-index.md` from a chat.

The exporter reads from the SQLite cache, never from disk. That keeps
it as fast as `armillary list` and as side-effect-free.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .cache import Cache
from .models import Project

# Columns in display order. Tuple of (header, key) where key is one of:
#  - "name", "type", "umbrella", "path", "last_modified" — straight from Project
#  - "status", "branch", "dirty", "last_commit", "last_commit_author" — from metadata
#  - "readme" — from metadata.readme_excerpt
_COLUMNS: tuple[tuple[str, str], ...] = (
    ("Name", "name"),
    ("Type", "type"),
    ("Status", "status"),
    ("Branch", "branch"),
    ("Dirty", "dirty"),
    ("Commits", "commit_count"),
    ("Work hours", "work_hours"),
    ("Last commit", "last_commit"),
    ("Last modified", "last_modified"),
    ("Path", "path"),
    ("Description", "readme"),
)


def render_repos_index(
    projects: list[Project],
    *,
    title: str = "armillary — projects index",
    generated_at: datetime | None = None,
) -> str:
    """Render a list of `Project`s as a self-contained markdown document.

    The output is intentionally human-readable AND machine-parseable:
    a heading, a generated-at line, the row count, and a markdown table.
    Empty fields render as `—`. README excerpts are stripped of pipes
    and newlines so they do not break the markdown table layout.
    """
    generated_at = generated_at or datetime.now()
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(
        f"Generated by `armillary export-index` at "
        f"{generated_at.strftime('%Y-%m-%d %H:%M:%S')}."
    )
    lines.append("")
    lines.append(f"**{len(projects)}** project(s) in the index.")
    lines.append("")

    if not projects:
        lines.append(
            "_Cache is empty. Run `armillary scan` to populate it, then re-export._"
        )
        lines.append("")
        return "\n".join(lines)

    headers = [h for h, _ in _COLUMNS]
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join(["---"] * len(headers)) + "|")
    for project in projects:
        cells = [_render_cell(project, key) for _, key in _COLUMNS]
        lines.append("| " + " | ".join(cells) + " |")

    lines.append("")
    return "\n".join(lines)


def write_repos_index(
    output_path: Path,
    *,
    db_path: Path | None = None,
    title: str = "armillary — projects index",
) -> int:
    """Read the cache, render the index, and write it to `output_path`.

    Returns the number of projects written. Creates parent directories
    as needed; overwrites the file if it already exists.
    """
    with Cache(db_path=db_path) as cache:
        projects = cache.list_projects()
    output_path = output_path.expanduser()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_repos_index(projects, title=title),
        encoding="utf-8",
    )
    return len(projects)


# --- Claude Code bridge ---------------------------------------------------

# Path (relative to ~/.claude/) of the repos-index written by the bridge.
# Claude Code's `@<path>` import syntax in CLAUDE.md resolves relative to
# the directory that contains CLAUDE.md, so we write the index inside
# `~/.claude/armillary/` and the import line reads `@armillary/repos-index.md`.
_BRIDGE_SUBDIR = "armillary"
_BRIDGE_FILENAME = "repos-index.md"
_CLAUDE_MD_IMPORT_LINE = "@armillary/repos-index.md"
_CLAUDE_MD_MARKER = (
    "# armillary projects index (managed by `armillary install-claude-bridge`)"
)


@dataclass(frozen=True)
class ClaudeBridgeStatus:
    """Current on-disk state of the Claude Code bridge integration."""

    bridge_path: Path
    bridge_installed: bool
    claude_md_path: Path
    claude_md_exists: bool
    claude_md_wired: bool


def claude_bridge_path(home: Path | None = None) -> Path:
    """Canonical location of the Claude Code bridge repos-index."""
    home = (home or Path.home()).expanduser()
    return home / ".claude" / _BRIDGE_SUBDIR / _BRIDGE_FILENAME


def claude_md_path(home: Path | None = None) -> Path:
    """Canonical top-level `CLAUDE.md` path in the user's home."""
    home = (home or Path.home()).expanduser()
    return home / ".claude" / "CLAUDE.md"


def get_claude_bridge_status(home: Path | None = None) -> ClaudeBridgeStatus:
    """Inspect whether the Claude bridge file and CLAUDE.md wiring exist."""
    bridge = claude_bridge_path(home)
    claude_md = claude_md_path(home)
    wired = False
    if claude_md.exists():
        try:
            wired = _CLAUDE_MD_IMPORT_LINE in claude_md.read_text(encoding="utf-8")
        except OSError:
            wired = False
    return ClaudeBridgeStatus(
        bridge_path=bridge,
        bridge_installed=bridge.exists(),
        claude_md_path=claude_md,
        claude_md_exists=claude_md.exists(),
        claude_md_wired=wired,
    )


def install_claude_bridge(
    *,
    home: Path | None = None,
    db_path: Path | None = None,
    with_claude_md: bool = False,
) -> tuple[Path, int, bool]:
    """Write the repos-index to the Claude Code bridge location.

    Writes `~/.claude/armillary/repos-index.md` (honors `home` override
    for tests). When `with_claude_md=True`, also appends an `@armillary/
    repos-index.md` import line to `~/.claude/CLAUDE.md` so every Claude
    Code session in the user's home loads the project table automatically.

    The append is idempotent — if either the `@armillary/repos-index.md`
    line or the managed-by marker is already present, CLAUDE.md is left
    untouched. Existing user content is preserved.

    Returns `(bridge_path, written_count, appended_to_claude_md)`.
    """
    bridge_path = claude_bridge_path(home)
    written = write_repos_index(bridge_path, db_path=db_path)

    appended = False
    if with_claude_md:
        claude_md = claude_md_path(home)
        appended = _ensure_claude_md_import(claude_md)

    return bridge_path, written, appended


def _ensure_claude_md_import(claude_md: Path) -> bool:
    """Idempotently append the armillary import block to CLAUDE.md.

    Returns True if we actually wrote to the file, False if the import
    line is already present. The idempotency check is on the literal
    `@armillary/repos-index.md` line only — NOT on the marker comment.
    If a user previously installed the block and later deletes the
    @-line while keeping (or not keeping) the marker, we re-add the
    import so Claude Code stays wired up. The marker is just a
    "who manages this block" signpost; it has no load-bearing role.
    """
    claude_md = claude_md.expanduser()
    existing = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""
    if _CLAUDE_MD_IMPORT_LINE in existing:
        return False

    # Ensure single blank-line separation from the existing tail.
    prefix = ""
    if existing and not existing.endswith("\n"):
        prefix = "\n"
    if existing and not existing.endswith("\n\n"):
        prefix += "\n"

    block = f"{prefix}{_CLAUDE_MD_MARKER}\n{_CLAUDE_MD_IMPORT_LINE}\n"
    claude_md.parent.mkdir(parents=True, exist_ok=True)
    with open(claude_md, "a", encoding="utf-8") as fh:
        fh.write(block)
    return True


# --- internals ------------------------------------------------------------


def _render_cell(project: Project, key: str) -> str:
    md = project.metadata
    value: str | None

    if key == "name":
        value = project.name
    elif key == "type":
        value = project.type.value
    elif key == "umbrella":
        value = str(project.umbrella)
    elif key == "path":
        value = str(project.path)
    elif key == "last_modified":
        value = project.last_modified.strftime("%Y-%m-%d")
    elif key == "status":
        value = md.status.value if md and md.status else None
    elif key == "branch":
        value = md.branch if md else None
    elif key == "dirty":
        # `dirty=0` is meaningful ("clean working tree"), distinct from
        # "metadata never extracted" → "—".
        if md is not None and md.dirty_count is not None:
            value = str(md.dirty_count)
        else:
            value = None
    elif key == "commit_count":
        value = str(md.commit_count) if md and md.commit_count is not None else None
    elif key == "work_hours":
        value = f"{md.work_hours:.1f}" if md and md.work_hours is not None else None
    elif key == "last_commit":
        value = (
            md.last_commit_ts.strftime("%Y-%m-%d") if md and md.last_commit_ts else None
        )
    elif key == "last_commit_author":
        value = md.last_commit_author if md else None
    elif key == "readme":
        value = md.readme_excerpt if md else None
    else:  # pragma: no cover — guarded by _COLUMNS
        value = None

    if value is None or value == "":
        return "—"
    return _escape_for_markdown_table(value)


def _escape_for_markdown_table(text: str) -> str:
    """Strip pipes and newlines so a value cannot break a markdown row.

    Pipes get replaced with `\\|` (escaped form, valid GFM). Line
    breaks collapse to spaces. We do not try to clamp length — long
    descriptions are fine and Claude/Codex parse them just as well as
    short ones.
    """
    return text.replace("\n", " ").replace("\r", " ").replace("|", "\\|").strip()
