"""Generate `repos-index.md` — a compact project table for the Claude Code bridge.

The bridge file is loaded into every Claude Code conversation via
`@armillary/repos-index.md` in `~/.claude/CLAUDE.md`. It must be small:
only ACTIVE/PAUSED projects, minimal columns (Status + Path), max 15 rows.
For the full project list, agents use the `armillary_projects` MCP tool.

The exporter reads from the SQLite cache, never from disk.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .cache import Cache
from .exclude_service import filter_excluded
from .models import Project, Status
from .status_override import filter_archived

_COLUMNS: tuple[tuple[str, str], ...] = (
    ("Status", "status"),
    ("Path", "path"),
)

_VISIBLE_STATUSES: frozenset[Status] = frozenset({Status.ACTIVE, Status.PAUSED})

_MAX_ROWS = 15


def render_repos_index(
    projects: list[Project],
    *,
    title: str = "armillary — projects index",
    generated_at: datetime | None = None,
) -> str:
    """Render a compact markdown table for the Claude Code bridge.

    Only ACTIVE/PAUSED projects are shown (up to 15). Paths are
    shortened with ``~``. A footer notes hidden projects and points
    to the MCP tool for the full list.
    """
    generated_at = generated_at or datetime.now()
    lines: list[str] = []

    eligible = [
        p for p in projects if p.metadata and p.metadata.status in _VISIBLE_STATUSES
    ]
    visible = eligible[:_MAX_ROWS]
    hidden = [p for p in projects if p not in visible]

    lines.append(f"# {title}")
    lines.append("")
    lines.append(
        f"Generated by `armillary` at {generated_at.strftime('%Y-%m-%d %H:%M:%S')}."
    )
    lines.append("")

    if not projects:
        lines.append(
            "_Cache is empty. Run `armillary scan` to populate it, then re-export._"
        )
        lines.append("")
        return "\n".join(lines)

    lines.append(f"**{len(visible)}** ACTIVE/PAUSED project(s).")
    lines.append("")

    headers = [h for h, _ in _COLUMNS]
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("|" + "|".join(["---"] * len(headers)) + "|")
    for project in visible:
        cells = [_render_cell(project, key) for _, key in _COLUMNS]
        lines.append("| " + " | ".join(cells) + " |")

    if hidden:
        counts = Counter(
            p.metadata.status.value if p.metadata and p.metadata.status else "UNKNOWN"
            for p in hidden
        )
        breakdown = ", ".join(f"{n} {s}" for s, n in counts.most_common())
        lines.append("")
        lines.append(
            f"_+{len(hidden)} hidden ({breakdown}). "
            f"Use `armillary_projects` MCP tool for the full list._"
        )

    lines.append("")
    return "\n".join(lines)


def write_repos_index(
    output_path: Path,
    *,
    db_path: Path | None = None,
    title: str = "armillary — projects index",
) -> int:
    """Read the cache, render the compact index, and write it to `output_path`.

    Returns the number of projects in cache. Creates parent directories
    as needed; overwrites the file if it already exists.
    """
    with Cache(db_path=db_path) as cache:
        projects = cache.list_projects()
    projects = filter_excluded(projects)
    projects = filter_archived(projects)
    output_path = output_path.expanduser()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_repos_index(projects, title=title),
        encoding="utf-8",
    )
    return len(projects)


# --- Claude Code bridge ---------------------------------------------------

_BRIDGE_SUBDIR = "armillary"
_BRIDGE_FILENAME = "repos-index.md"
_CLAUDE_MD_IMPORT_LINE = "@armillary/repos-index.md"
_CLAUDE_MD_MARKER = (
    "# armillary projects index (managed by `armillary install-claude-bridge`)"
)


@dataclass(frozen=True)
class ClaudeBridgeStatus:
    """Current on-disk state of the Claude Code bridge integration."""

    bridge_path: Path
    bridge_installed: bool
    claude_md_path: Path
    claude_md_exists: bool
    claude_md_wired: bool


def claude_bridge_path(home: Path | None = None) -> Path:
    """Canonical location of the Claude Code bridge repos-index."""
    home = (home or Path.home()).expanduser()
    return home / ".claude" / _BRIDGE_SUBDIR / _BRIDGE_FILENAME


def claude_md_path(home: Path | None = None) -> Path:
    """Canonical top-level `CLAUDE.md` path in the user's home."""
    home = (home or Path.home()).expanduser()
    return home / ".claude" / "CLAUDE.md"


def get_claude_bridge_status(home: Path | None = None) -> ClaudeBridgeStatus:
    """Inspect whether the Claude bridge file and CLAUDE.md wiring exist."""
    bridge = claude_bridge_path(home)
    claude_md = claude_md_path(home)
    wired = False
    if claude_md.exists():
        try:
            wired = _CLAUDE_MD_IMPORT_LINE in claude_md.read_text(encoding="utf-8")
        except OSError:
            wired = False
    return ClaudeBridgeStatus(
        bridge_path=bridge,
        bridge_installed=bridge.exists(),
        claude_md_path=claude_md,
        claude_md_exists=claude_md.exists(),
        claude_md_wired=wired,
    )


def install_claude_bridge(
    *,
    home: Path | None = None,
    db_path: Path | None = None,
    with_claude_md: bool = False,
) -> tuple[Path, int, bool]:
    """Write the compact repos-index to the Claude Code bridge location.

    Writes `~/.claude/armillary/repos-index.md` (honors `home` override
    for tests). When `with_claude_md=True`, also appends an `@armillary/
    repos-index.md` import line to `~/.claude/CLAUDE.md`.

    Returns `(bridge_path, written_count, appended_to_claude_md)`.
    """
    bridge_path = claude_bridge_path(home)
    written = write_repos_index(bridge_path, db_path=db_path)

    appended = False
    if with_claude_md:
        claude_md = claude_md_path(home)
        appended = _ensure_claude_md_import(claude_md)

    return bridge_path, written, appended


def _ensure_claude_md_import(claude_md: Path) -> bool:
    """Idempotently append the armillary import block to CLAUDE.md.

    Returns True if we actually wrote to the file, False if the import
    line is already present.
    """
    claude_md = claude_md.expanduser()
    existing = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""
    if _CLAUDE_MD_IMPORT_LINE in existing:
        return False

    prefix = ""
    if existing and not existing.endswith("\n"):
        prefix = "\n"
    if existing and not existing.endswith("\n\n"):
        prefix += "\n"

    block = f"{prefix}{_CLAUDE_MD_MARKER}\n{_CLAUDE_MD_IMPORT_LINE}\n"
    claude_md.parent.mkdir(parents=True, exist_ok=True)
    with open(claude_md, "a", encoding="utf-8") as fh:
        fh.write(block)
    return True


# --- internals ------------------------------------------------------------


def _render_cell(project: Project, key: str) -> str:
    md = project.metadata

    if key == "status":
        value = md.status.value if md and md.status else None
    elif key == "path":
        try:
            value = "~/" + str(project.path.relative_to(Path.home()))
        except ValueError:
            value = str(project.path)
    else:  # pragma: no cover
        value = None

    if value is None or value == "":
        return "—"
    return value.replace("|", "\\|").replace("\n", " ").replace("\r", "")
